aliases: []
creation_timestamp: 1739195706614
current_stage: None
description: ''
last_updated_timestamp: 1739195706614
name: logistic_regression
run_id: 939817291cba41449a81e2d5fa70ff97
run_link: ''
source: /home/chen/Desktop/lectures/10x-ML-engineer/mlflow/mlruns/497038454285270979/939817291cba41449a81e2d5fa70ff97/artifacts/logistic_regression
status: READY
status_message: null
storage_location: /home/chen/Desktop/lectures/10x-ML-engineer/mlflow/mlruns/497038454285270979/939817291cba41449a81e2d5fa70ff97/artifacts/logistic_regression
user_id: null
version: 1
